[development]
dynaconf_merge = true

[development.db]
echo = true

[development.server]
log_level = "debug"
access_log = true
reload = true
cors_origins = ["*"]

[production]
dynaconf_merge = true

[production.db]
echo = false

[production.server]
log_level = "error"
reload = false

[testing]
dynaconf_merge = true

[testing.server]
cors_origins = ["*"]
