[development]
dynaconf_merge = true

[development.db]
echo = true

[development.server]
access_log = true
cors_origins = ["*"]
log_level = "debug"
reload = true

[production]
dynaconf_merge = true

[production.db]
echo = false

[production.server]
log_level = "error"
reload = false

[testing]
dynaconf_merge = true

[testing.server]
cors_origins = ["*"]
